# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.6'
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run check:ci

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.6'
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run test:cov
    - uses: codecov/codecov-action@v4
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
        file: lcov.info
    
  build:
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.6'
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
